name:                haskell-typing-game
version:             0.1.0.0
github:              "githubuser/haskell-typing-game"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-typing-game#readme>

dependencies:
- base >= 4.7 && < 5
- text
- ncurses
- brick
- lens
- vty
- selda
- selda-sqlite
- req
- modern-uri
- bytestring
- scalpel
- regex-tdfa
- hspec
- aeson
- aeson-pretty
- directory
- random
- safe

library:
  source-dirs: src

executables:
  haskell-typing-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-typing-game

tests:
  haskell-typing-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-typing-game

default-extensions:
  # Trivial lifting of standards-imposed limitations
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  # Syntactic conveniences
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  # Extensions to the deriving mechanism
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  # Lightweight syntactic adjustments
  - BangPatterns
  - KindSignatures
  - TypeOperators
  # Polymorphic string literals
  - OverloadedStrings
  # Simple extensions to aid type annotation
  - ScopedTypeVariables
  - TypeApplications
  # Simple extensions to the Haskell type system
  - ConstraintKinds
  - RankNTypes
  # Intermediate syntactic adjustments
  - ApplicativeDo
  - DefaultSignatures
  - PatternSynonyms
  # Intermediate extensions to the Haskell type system
  - ExistentialQuantification
  - FunctionalDependencies
  - GADTs
  # Advanced extensions to the Haskell type system
  - DataKinds
  - TypeFamilies
  - TypeFamilyDependencies

  # Other required by libraries
  - QuasiQuotes
  - TemplateHaskell